name: Python Script Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies (if any)
      run: |
        # If you have dependencies to install, add the installation command here
        # For example:
        # pip install -r AcortadorURL/requirements.txt

    - name: Run Python script
      run: |
        cd AcortadorURL
        python run.py
