name: Python Script Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        cd AcortadorURL
        python -m pip install --upgrade pip
        pip install -r requirements.txt   # Si tienes un archivo de requerimientos
        pip install Flask                # Instala Flask

    - name: Run Python script
      run: |
        cd AcortadorURL
        python run.py > /dev/null 2>&1 &   # Ejecuta Flask en segundo plano
        sleep 3   # Espera un momento para que Flask se inicie correctamente
        curl -sSf http://127.0.0.1:5000   # Realiza una solicitud HTTP para verificar que Flask está corriendo
        kill $(jobs -p)   # Detiene el proceso de Flask después de verificar que está corriendo correctamente
